# Generated by Django 5.2.8 on 2025-11-21 16:41

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Name of the product.', max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly identifier for the product.', max_length=255, null=True, unique=True)),
                ('image', models.ImageField(blank=True, help_text='Image representing the product.', null=True, upload_to='products/images/')),
                ('description', ckeditor.fields.RichTextField(blank=True, help_text='Detailed description of the product.', null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, help_text='Price of the product.', max_digits=10)),
                ('percentage', models.PositiveIntegerField(default=0, help_text='Discount percentage for the product.')),
                ('availability', models.CharField(blank=True, help_text='Availability status of the product (e.g., In Stock, Out of Stock).', max_length=100, null=True)),
                ('shipping_details', models.CharField(blank=True, help_text='Shipping information for the product.', max_length=255, null=True)),
                ('weight', models.CharField(blank=True, help_text='Weight of the product.', max_length=50, null=True)),
                ('stock', models.PositiveIntegerField(default=1, help_text='Available stock quantity.')),
                ('is_available', models.BooleanField(default=True, help_text='Availability status of the product.')),
                ('views_count', models.PositiveIntegerField(default=0, help_text='Views count: ')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the product was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the product was last updated.')),
                ('category', models.ForeignKey(help_text='Category to which the product belongs.', limit_choices_to={'category_type': 'product'}, on_delete=django.db.models.deletion.CASCADE, related_name='products_category', to='category.category')),
                ('tags', models.ManyToManyField(blank=True, help_text='Tags associated with the product.', related_name='products_tags', to='category.tag')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['name'],
            },
        ),
    ]
