# Generated by Django 5.2.8 on 2025-11-20 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, db_index=True, help_text='Enter your email to subscribe', max_length=150, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Subscribed Email',
                'verbose_name_plural': 'Subscribed Emails',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['email'], name='common_sube_email_6856af_idx')],
            },
        ),
    ]
