# Generated by Django 5.2.8 on 2025-11-20 17:55

import ckeditor.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subemail',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='The date and time when the email was subscribed'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Name of the banner', max_length=225, unique=True)),
                ('image', models.ImageField(blank=True, help_text='Upload banner image', null=True, upload_to='banners/')),
                ('description', ckeditor.fields.RichTextField(blank=True, help_text='Description of the banner', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when the banner was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time when the banner was last updated')),
                ('parent', models.ForeignKey(blank=True, help_text='Parent banner if applicable', limit_choices_to={'parent__isnull': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='common.banner')),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['name'], name='common_bann_name_ab06f3_idx')],
            },
        ),
    ]
