# Generated by Django 5.2.8 on 2025-11-14 05:37

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Category name', max_length=225, unique=True)),
                ('slug', models.SlugField(blank=True, help_text='Category slug for URL', max_length=225, null=True, unique=True)),
                ('category_type', models.CharField(blank=True, choices=[('product', 'Product'), ('article', 'Article')], default=None, help_text='Select category type', max_length=50, null=True)),
                ('image', models.ImageField(blank=True, help_text='Image representing the category', null=True, upload_to='categories/')),
                ('description', ckeditor.fields.RichTextField(blank=True, help_text='Description of the category', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the category was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the category was last updated')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='category_name_idx'), models.Index(fields=['slug'], name='category_slug_idx')],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Tag name', max_length=225, unique=True)),
                ('slug', models.SlugField(blank=True, help_text='Tag slug for URL', max_length=225, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the tag was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the tag was last updated')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='tag_name_idx'), models.Index(fields=['slug'], name='tag_slug_idx')],
            },
        ),
    ]
