# Generated by Django 5.2.8 on 2025-11-20 18:33

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='The name of the article.', max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, help_text='A URL-friendly slug for the article.', max_length=255, null=True, unique=True)),
                ('image', models.ImageField(blank=True, help_text='An image representing the article.', null=True, upload_to='articles/images/')),
                ('description', ckeditor.fields.RichTextField(blank=True, help_text='A detailed description of the article.', null=True)),
                ('views_count', models.PositiveIntegerField(default=0, help_text='The number of times the article has been viewed.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The time when the article was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The time when the article was last updated.')),
                ('author', models.ForeignKey(help_text='The author of the article.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles_author', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(help_text='The category to which this article belongs.', limit_choices_to={'category_type': 'product'}, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='category.category')),
                ('tags', models.ManyToManyField(blank=True, help_text='Tags associated with this article.', related_name='articles_tags', to='category.tag')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['name'], name='article_name_idx'), models.Index(fields=['slug'], name='article_slug_idx'), models.Index(fields=['category'], name='category_article_idx'), models.Index(fields=['author'], name='author_article_idx')],
            },
        ),
    ]
