# Generated by Django 5.2.8 on 2025-11-21 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(help_text='The category to which this article belongs.', limit_choices_to={'category_type': 'article'}, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='category.category'),
        ),
    ]
