# Generated by Django 5.2.7 on 2025-11-03 10:13

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the person contacting.', max_length=100)),
                ('email', models.EmailField(blank=True, help_text='Email address of the person contacting.', max_length=254, null=True)),
                ('message', ckeditor.fields.RichTextField(blank=True, help_text='The message content from the contact form.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the message was created.')),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
            },
        ),
    ]
