# Generated by Django 5.2.7 on 2025-11-03 10:18

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='email',
            field=models.EmailField(default=0, help_text='Email address of the person contacting.', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='message',
            field=ckeditor.fields.RichTextField(help_text='The message content from the contact form.'),
        ),
    ]
