# Generated by Django 5.2.8 on 2025-11-21 17:47

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0002_product_product_name_idx_product_product_slug_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'New'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='new', help_text='Current status of the order', max_length=20)),
                ('first_name', models.CharField(db_index=True, help_text='First name of the person who placed the order', max_length=100)),
                ('last_name', models.CharField(db_index=True, help_text='Last name of the person who placed the order', max_length=100)),
                ('email', models.EmailField(db_index=True, help_text='Contact email for the order', max_length=100)),
                ('phone_number', models.CharField(db_index=True, help_text='Contact phone number for the order', max_length=20)),
                ('address', models.CharField(help_text='Shipping address for the order', max_length=255)),
                ('notes', ckeditor.fields.RichTextField(blank=True, help_text='Additional notes or instructions for the order', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when the order was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time when the order was last updated')),
                ('user', models.ForeignKey(help_text='The user who placed the order', on_delete=django.db.models.deletion.CASCADE, related_name='order_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, help_text='The quantity of the product ordered')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, help_text='The price of the product at the time of order', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when the order item was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time when the order item was last updated')),
                ('order', models.ForeignKey(help_text='The order to which this item belongs', on_delete=django.db.models.deletion.CASCADE, related_name='order_item_order', to='order.order')),
                ('product', models.ForeignKey(help_text='The product included in this order item', on_delete=django.db.models.deletion.CASCADE, related_name='order_item_product', to='product.product')),
            ],
            options={
                'verbose_name': 'Order Item',
                'verbose_name_plural': 'Order Items',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user'], name='order_order_user_id_a7f1ea_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['first_name'], name='order_order_first_n_6d6a84_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['last_name'], name='order_order_last_na_91f97b_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['email'], name='order_order_email_9aefce_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['phone_number'], name='order_order_phone_n_4e7129_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['order'], name='order_order_order_i_854de1_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['product'], name='order_order_product_ed1645_idx'),
        ),
    ]
